travis:
  secure:
    BINSTAR_TOKEN: Xv3IrH5NZUCmjLHckMHQ4D7JS7GNkmvFuXz2h6Aj/f7t3euvidWVcHGz27xDFVPI3uD9hRBNpCinJzK6+DTH4Z7Rge2scWm0UFur3eEwftghL8FN2c77LmUAxx7R9KxPamG0O0sBeybYNr+mKgFpJbPkCYzqbxFDWJJ7+EYLRADoqH08w3df5RctqBMmGGZ0eXthao5iARLW5yfK2zKReCN3d5MTQXgPAA3CfGDrlULLS1iVUlZnznJqsYifv5zIL5r73ZFQectIUaTT4ycs0nyKdkYV8yhDIFu7MiOgFBtarQ2TSB/BJY8A79GhA/x+xsWMDvtRClFR2fjBrGHFL/Pu9AvepVrIjluwrXi7klKO/PJrYUnhK9p6+KXmu+fpUHAfjle7XEKnbf/hz8Tr2lsn+hbo+kdKyV7u9L4J/jvXPivgirr7ekg7BaIOgsuJSSAo//D/H8juOKe//nh4KjXdQEylWFww3gmHAWIh/bhMOK8mJZbJA+mrBEKlhos103tRc9dQOPYNDlZ1LIEgo+Q7fSxI8hVqvcDJqBjvtoVyowTEtoHwwu67zMnUrZHjPU5LiVirO/PzzpVCpLHvNkmJQeqaZzPPJiyyMs5z9hrv2ZJJkPRZSdi2N49m5+sV54vssohMmDTIMI0oBcb0fDT41cFAasSo+BR5UGA/0EM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
